package com.pickle.sys.service;



import com.pickle.sys.bean.GgCodeTab;
import com.pickle.utils.base.IBaseService;

import java.util.List;

/**
*  generated by ztax mybatis plugin
*/

public interface IGgCodeTabExtService extends IBaseService<GgCodeTab> {

    List<GgCodeTab> queryListByCodeTab(String codeType);

}