jdbc-connection-drive-class=com.mysql.cj.jdbc.Driver
jdbc-connection-url=jdbc:mysql://127.0.0.1:3306/pickle?characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
jdbc-connection-username=root
jdbc-connection-password=123456

manage-models=pickle-procedure
manage-package=procedure

generator-user-name=wanglong
fl-flag=2

#lei-dou-ji-cheng-ta
bean-root-class=com.pickle.utils.base.BaseBean

table-name=wx_cd_cdyy


